### ISSUE TITLE
Add Scripture Deciphering Feature

### ISSUE THREAD

**Issue by serenesummwr** [sereneq1/Scripture#1]
# Scripture Deciphering Feature Implementation

## Overview
Add a new scripture deciphering feature that automatically detects scriptures with trigger lore, recognizes scripture types, and replaces their lore with 4 random enchantments from configurable pools.

### 1. Automatic Detection
- Detect scriptures containing trigger lines:
  - "Scriptures can be deciphered"
  - "by using an Enchantment Table"
- Integrate with existing `PaperToCoinHolder.handleCoinInsertion()` method

### 2. Scripture Type Recognition
- Identify scripture type from display name (e.g., "Ember Scripture", "Tide Scripture")
- Use ItemsAdder's `CustomStack.byItemStack()` for type detection

### 3. Random Enchantment Selection
- Select exactly 4 distinct enchantments from scripture-specific pools
- Randomize levels within configured min/max ranges
- Support both vanilla and custom enchantments

### 4. Lore Replacement
- Replace scripture lore with 4 randomly chosen enchantments
- Maintain proper formatting with enchantment levels
- Preserve original scripture functionality

### 5. Configuration System
- Add `scripture_pools` section to config.yml
- Define enchantment pools per scripture type
- Set min/max levels for each enchantment
- Configure sound effects and visual feedback

### New Components Needed:
1. **ScriptureDecipher.java** - Core deciphering logic
2. **Config updates** - Add scripture pools configuration
3. **PaperToCoinHolder modifications** - Integration with existing GUI

### Integration Points:
- Modify `readScriptureLore()` method to detect trigger lines
- Add deciphering logic before normal enchantment processing
- Maintain compatibility with existing enchanting system

## Configuration Structure
```yaml
scripture_deciphering:
  enabled: true
  trigger_lines:
    - "Scriptures can be deciphered"
    - "by using an Enchantment Table"
  sound_effects:
    decipher_success: "BLOCK_ENCHANTMENT_TABLE_USE"
    decipher_volume: 1.0
    decipher_pitch: 1.2
  
scripture_pools:
  ember_scripture:
    enchantments:
      fire_aspect:
        min_level: 1
        max_level: 2
        weight: 10
      flame:
        min_level: 1
        max_level: 1
        weight: 8
      # ... more enchantments
  tide_scripture:
    enchantments:
      aqua_affinity:
        min_level: 1
        max_level: 1
        weight: 10
      # ... more enchantments
```

## Acceptance Criteria
- [ ] Scripture detection works for configured trigger lines
- [ ] Scripture type recognition from display names
- [ ] Random enchantment selection (exactly 4 distinct)
- [ ] Lore replacement maintains proper formatting
- [ ] Configuration system is fully functional
- [ ] Integration doesn't break existing functionality
- [ ] Sound effects and visual feedback work
- [ ] Supports both vanilla and custom enchantments
